server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistic
    username: postgres
    password: changeme
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
